// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8STbxK3jERAFtBuBv_OHWAY7P8me0Z-8',
    appId: '1:683072569716:web:1c7d3f9a74456afb10ec21',
    messagingSenderId: '683072569716',
    projectId: 'smaetmood',
    authDomain: 'smaetmood.firebaseapp.com',
    storageBucket: 'smaetmood.appspot.com',
    measurementId: 'G-53M5PBB3GN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEYlBrazxABhaFAkp0aN_OsWXt4vLzbSI',
    appId: '1:683072569716:android:6d00122f67a0be6110ec21',
    messagingSenderId: '683072569716',
    projectId: 'smaetmood',
    storageBucket: 'smaetmood.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAc5hG3v_tqHHlXnPG-WQdMwOVOU6MRwMo',
    appId: '1:683072569716:ios:dcae45c927ebf43e10ec21',
    messagingSenderId: '683072569716',
    projectId: 'smaetmood',
    storageBucket: 'smaetmood.appspot.com',
    iosBundleId: 'com.example.new_app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAc5hG3v_tqHHlXnPG-WQdMwOVOU6MRwMo',
    appId: '1:683072569716:ios:589a0cf256cc91a110ec21',
    messagingSenderId: '683072569716',
    projectId: 'smaetmood',
    storageBucket: 'smaetmood.appspot.com',
    iosBundleId: 'com.example.new_app.RunnerTests',
  );
}
